version: '3.8'

services:
  db:
    image: postgres:14
    container_name: estacionamento_db
    environment:
      POSTGRES_DB: estacionamento
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - estacionamento_db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: estacionamento_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/estacionamento
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  estacionamento_db_data:
    driver: local