services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - estacionamento-network

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: estacionamento
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - estacionamento-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "estacionamento"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

networks:
  estacionamento-network:
    driver: bridge

volumes:
  postgres_data:
