spring:
  datasource:
    url: jdbc:postgresql://db:5432/estacionamento
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  error:
    include-stacktrace: never